program: tumor_detect.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.1
  decay:
    min: 0.000001 * 0.0001 * 16/256. # 0.000001 * lr_lower * batch_size_ft/256.
    max: 0.001 * 0.1 * 16/256.
  optimizer:
    values: ["sgd"]